# Generated by Django 4.2.5 on 2023-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hello',
            name='video',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
