# Generated by Django 5.0.2 on 2024-05-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSnapper',
            fields=[
                ('videoid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
